system42.on("splash:ready",function(){
$store.set("progman/res/Accessories/3D.lnk42",        {"exe":"3d"}    )
$store.set("progman/res/Accessories/ANSI Love.lnk42",        {"exe":"ansi","icon":"apps/ansilove.png"}    )
$store.set("progman/res/Accessories/ASCII Gallery.lnk42",        {"exe":"ascii","icon":"/c/files/images/icons/90s123.png"}    )
$store.set("progman/res/Accessories/Calc.lnk42",        {"exe":"calc"}    )
$store.set("progman/res/Accessories/CodeMirror.lnk42",        {"exe":"code"}    )
$store.set("progman/res/Accessories/Defrag.lnk42",        {"exe":"defrag"}    )
$store.set("progman/res/Accessories/DERG32.EXE.lnk42",        {"exe":"marburg","icon":"apps/sick.png"}    )
$store.set("progman/res/Accessories/Doctor Marburg.lnk42",        {"exe":"doctor"}    )
$store.set("progman/res/Accessories/FX.lnk42",        {"exe":"fx"}    )
$store.set("progman/res/Accessories/HexEd.lnk42",        {"exe":"hexed"}    )
$store.set("progman/res/Accessories/MANIFESTO.lnk42",        {"exe":"manifesto"}    )
$store.set("progman/res/Accessories/Piskel.lnk42",        {"exe":"piskel"}    )
$store.set("progman/res/Accessories/Speech.lnk42",        {"exe":"speech"}    )
$store.set("progman/res/Accessories/Terminal.lnk42",        {"exe":"hello","icon":"apps/terminal.png"}    )
$store.set("progman/res/Accessories/Virtual Girl.lnk42",        {"exe":"lisa","icon":"apps/annaKournikova.gif"}    )
$store.set("progman/res/Accessories/Virtual PC.lnk42",        {"exe":"virtualpc","icon":"apps/inception.png"}    )
$store.set("progman/res/Games/Adobe Pizza Player™.lnk42",        {"exe":"flash"}    )
$store.set("progman/res/Games/Brian Sweeper.lnk42",        {"exe":"mines"}    )
$store.set("progman/res/Games/DMG.lnk42",        {"exe":"dmg"}    )
$store.set("progman/res/Games/DOSBox.lnk42",        {"exe":"dosbox"}    )
$store.set("progman/res/Games/GAFA 3D.lnk42",        {"exe":"castlegafa"}    )
$store.set("progman/res/Games/Half-Life 3.lnk42",        {"icon":"/c/sys/skins/w93/apps/hl3.png","exe":"hl3","title":"Half-Life 3"}    )
$store.set("progman/res/Games/Kof'93.lnk42",        {"exe":"kof93","icon":"/c/programs/kof93/gief.gif"}    )
$store.set("progman/res/Games/Maze 3D.lnk42",        {"exe":"maze"}    )
$store.set("progman/res/Games/NES.lnk42",        {"exe":"nes"}    )
$store.set("progman/res/Games/Pokéglitch.lnk42",        {"exe":"/c/files/roms/dmg/fail/Pokeglitch.gb","title":"Pokéğ̭̤ͬ̋ͭͬ̏ͪl̥̠ͦiṫ͚̠͇̠̮̯̍ͬ͗̂c̙ͭ͛̄h̫̦ͯ͆ͯ̀̓̂ͫ","icon":"apps/helix.png"}    )
$store.set("progman/res/Games/PokéRainbow.lnk42",        {"exe":"pokerainbow"}    )
$store.set("progman/res/Games/Progress Quest.lnk42",        {"exe":"progressquest","icon":"apps/progressquest.gif"}    )
$store.set("progman/res/Games/Robby.lnk42",        {"exe":"robby"}    )
$store.set("progman/res/Games/SAE.lnk42",        {"exe":"sae"}    )
$store.set("progman/res/Games/SIM 93.lnk42",        {"exe":"sim93","icon":"/c/sys/skins/w93/apps/visualNovel.png"}    )
$store.set("progman/res/Games/SMS.lnk42",        {"exe":"sms"}    )
$store.set("progman/res/Games/Solitude.lnk42",        {"exe":"solitude"}    )
$store.set("progman/res/Multimedia/Acid Box 93.lnk42",        {"exe":"acidbox"}    )
$store.set("progman/res/Multimedia/Bananamp.lnk42",        {"exe":"bananamp"}    )
$store.set("progman/res/Multimedia/Byte Beat.lnk42",        {"exe":"bytebeat"}    )
$store.set("progman/res/Multimedia/G80.M3U.lnk42",        {"exe":"g80.m3u"}    )
$store.set("progman/res/Multimedia/Glitch GRLZ.lnk42",        {"exe":"/c/files/roms/dmg/fail/Glitch_Grrrlz-Vol01.gbc","icon":"apps/glitchgirlz.png"}    )
$store.set("progman/res/Multimedia/HAMPSTER.lnk42",        {"exe":"hampster"}    )
$store.set("progman/res/Multimedia/lenna.png.lnk42",        {"exe":"lenna"}    )
$store.set("progman/res/Multimedia/LSDJ.lnk42",        {"exe":"/c/files/roms/dmg/music/lsdj3_1_9_demo.gb","icon":"apps/lsdj.png"}    )
$store.set("progman/res/Multimedia/MIDI Jukebox.lnk42",        {"exe":"midi","icon":"/c/sys/skins/w93/apps/midiPlayer.png"}    )
$store.set("progman/res/Multimedia/Modded BeepBox.lnk42",        {"exe":"beepbox"}    )
$store.set("progman/res/Multimedia/Nanoloop.lnk42",        {"exe":"/c/files/roms/dmg/music/nanoloop171d.gb","icon":"apps/nanoloop.png"}    )
$store.set("progman/res/Multimedia/Poney Jockey.lnk42",        {"exe":"pony"}    )
$store.set("progman/res/Multimedia/Puke Data.lnk42",        {"exe":"pd"}    )
$store.set("progman/res/Multimedia/Recorder.lnk42",        {"exe":"recorder","icon":"/c/sys/skins/w93/apps/recorder.png"}    )
$store.set("progman/res/Multimedia/Star Wars.avi.lnk42",        {"exe":"starwars","icon":"apps/yoda.gif"}    )
$store.set("progman/res/Network/93 Realms.lnk42",        {"exe":"93realms","icon":"/c/files/images/icons/wizard.png"}    )
$store.set("progman/res/Network/Arena 93 multiplayer.lnk42",        {"exe":"arena93"}    )
$store.set("progman/res/Network/Cat Explorer.lnk42",        {"exe":"catex"}    )
$store.set("progman/res/Network/Network.lnk42",        {"icon":"/c/files/images/icons/burger.png","exe":"/a/progman/res/Network/","title":"Network"}    )
$store.set("progman/res/Network/Potato.yt.lnk42",        {"exe":"potato","icon":"/c/files/images/icons/potato.png"}    )
$store.set("progman/res/Network/Trollbox.lnk42",        {"exe":"trollbox","icon":"apps/chat.gif"}    )
$store.set("progman/res/Other/Contact us.lnk42",        {"exe":"contact","icon":"mail.png"}    )
$store.set("progman/res/Other/Corglitch.lnk42",        {"exe":"glitch","icon":"apps/corgi.gif"}    )
$store.set("progman/res/Other/Credits.txt.lnk42",        {"exe":"iframe /c/credits.html --width=450 --height=\"300\" --bodyClass=\"skin_light skin_inset\""}    )
$store.set("progman/res/Other/Hydra.exe.lnk42",        {"exe":"hydra","icon":"apps/hydra.png"}    )
$store.set("progman/res/Other/OLDEST GIF OF THE INTERWEBZ.gif.lnk42",        {"exe":"/c/files/images/gif/wind.gif"}    )
$store.set("progman/res/Other/Take this.lnk42",        {"exe":"takethis"}    )
$store.set("progman/res/Other/Totally not a virus.Trust me...im a dolphin.lnk42",        {"exe":"gravity","icon":"apps/dolphin.png"}    )
$store.set("progman/res/Other/What If.lnk42",        {"exe":"whatif"}    )
$store.set("progman/Program Managar/Accessories.lnk42",        {"icon":"/c/files/images/icons/burger.png","exe":"/a/progman/res/Accessories/","title":"Accessories"}    )
$store.set("progman/Program Managar/Games.lnk42",        {"icon":"/c/files/images/icons/burger.png","exe":"/a/progman/res/Games/","title":"Games"}    )
$store.set("progman/Program Managar/Multimedia.lnk42",        {"icon":"/c/files/images/icons/burger.png","exe":"/a/progman/res/Multimedia/","title":"Multimedia"}    )
$store.set("progman/Program Managar/Network.lnk42",        {"icon":"/c/files/images/icons/burger.png","exe":"/a/progman/res/Network/","title":"Network"}    )
$store.set("progman/Program Managar/Other.lnk42",        {"icon":"/c/files/images/icons/burger.png","exe":"/a/progman/res/Other/","title":"Other"}    )

localforage.removeItem("boot/install.js")
setTimeout(function(){document.location.reload()},1200)
})