le._apps.reboot.exec = function(){
  le._settings.sounds.shutdown = "/c/files/sounds/shutdown.mp3";$audio('shutdown').play(); var head = document.head.innerHTML; document.write('<head>'+head+'</head><body style="background: #636363; color: white;"><h1 id="texxt" style="font-family: Arial Black;"></h1><img width="600" src="https://i.imgur.com/vuCXT9O.gif"><audio autoplay loop><source src="https://www.albinoblacksheep.com/audio/mp3/Nyanyanyanyanyanyanya.mp3" type="audio/mp3"></audio><br><br><br><br><div style="color: white;"><h1>Credits</h1><br><b>MEMZ Trojan made by Leurak</b><br><u>Windows 93 version created by:</u><br><p>Blockly806</p><p>'+"'HOST'"+'</p><br><br></div></body>');
  setTimeout(function(){document.getElementById('texxt').innerText = "You"}, 1000);setTimeout(function(){document.getElementById('texxt').innerText = "Your co"}, 1150);setTimeout(function(){document.getElementById('texxt').innerText = "Your compu"}, 1300);setTimeout(function(){document.getElementById('texxt').innerText = "Your computer"}, 1450);setTimeout(function(){document.getElementById('texxt').innerText = "Your computer has"}, 1600);setTimeout(function(){document.getElementById('texxt').innerText = "Your computer has bee"}, 1750);setTimeout(function(){document.getElementById('texxt').innerText = "Your computer has been destr"}, 1900);setTimeout(function(){document.getElementById('texxt').innerText = "Your computer has been destroye"}, 2050);setTimeout(function(){document.getElementById('texxt').innerText = "Your computer has been destroyed by"}, 2200);setTimeout(function(){document.getElementById('texxt').innerText = "Your computer has been destroyed by MEM"}, 2350);setTimeout(function(){document.getElementById('texxt').innerText = "Your computer has been destroyed by MEMZ tr"}, 2500);setTimeout(function(){document.getElementById('texxt').innerText = "Your computer has been destroyed by MEMZ troja"}, 2650);setTimeout(function(){document.getElementById('texxt').innerText = "Your computer has been destroyed by MEMZ trojan. E"}, 2800);setTimeout(function(){document.getElementById('texxt').innerText = "Your computer has been destroyed by MEMZ trojan. Enjo"}, 2950);setTimeout(function(){document.getElementById('texxt').innerText = "Your computer has been destroyed by MEMZ trojan. Enjoy th"}, 3100);setTimeout(function(){document.getElementById('texxt').innerText = "Your computer has been destroyed by MEMZ trojan. Enjoy the Ny"}, 3250);setTimeout(function(){document.getElementById('texxt').innerText = "Your computer has been destroyed by MEMZ trojan. Enjoy the Nyan C"}, 3400);setTimeout(function(){document.getElementById('texxt').innerText = "Your computer has been destroyed by MEMZ trojan. Enjoy the Nyan Cat."}, 3550);setTimeout(function(){document.getElementById('texxt').innerText = "Your computer has been destroyed by MEMZ trojan. Enjoy the Nyan Cat..."}, 3700);
  $audio('alert').stop();$audio('error').stop();$audio('alert')._src = "";$audio('error')._src = "";
};
le._apps.shutdown.exec = function(){$exe('reboot')}; le._apps.format.exec = function(){var ne='THERE IS NO ESCAPE FROM TEH MEMZ';$notif(ne);$notif(ne);$notif(ne)};
((e,t)=>{document.title = "MEMDOWS93";$exe("textarea");$window.current.el.body.firstChild.value="YOUR COMPUTER HAS BEEN FUCKED BY THE MEMZ TROJAN (not really).\nYour computer won't boot up again, so use it as long as you can!\n:D\nTrying to kill MEMZ will cause your system to be destroyed instantly, so don't try it :D\n";$window.current.changeTitle('Untitled - Notepad');$window.current.changeSize({width: 750, height: 400});var n=new Image;n.src='/c/sys/skins/w93/' + $io.arr.random(['error','alert']) + '.png';var a=document.createElement("canvas"),i=[];a.style.position="absolute",a.style.zIndex="1e5",a.style.top="0",a.style.left="0",a.style.pointerEvents="none",a.width=innerWidth,a.height=innerHeight,le._dom.screen.appendChild(a),e(e=>{a.width=innerWidth,a.height=innerHeight;for(var t=0;t<i.length;t++)a.getContext("2d").drawImage(n,i[t][0],i[t][1])},1),t(t=>{e(e=>{i.push([Math.random()*innerWidth,Math.random()*innerHeight])},1e3)},5e3+1e4*Math.random()),t(t=>{e(e=>{document.querySelectorAll('span').forEach((v) => {v.style.direction = "rt1"; v.style['unicode-bidi'] = "bidi-override";}); $alert({msg:"Still using this computer?",center:!1,btnOk:"OK",title:"lol",animationOut:"none",icon:"https://i.imgur.com/zzz1KA1.png"})},3500)},1e4+2e4*Math.random()),t(t=>{e(e=>{$exe(["whatif","acidbox","terminal","catex","mines","beepbox","b","textarea","starwars","defrag","/a/trash","trollbox","recorder","pony","calc","speech","marburg","hydra","/c/files/music/","/a/boot/","/c/libs/codef/","3d xD","solitude","clippy","lisa"][Math.floor(10*Math.random())])},5e3)},1e4+3e4*Math.random()),t(t=>{e(e=>{$exe("fx invert");$exe("fx invert .s42_taskbar");$exe("fx invert .ui_icon");$exe("fx invert .ui_icon");},967);},7e3+1e4*Math.random()),t(t=>{e(e=>{$exe('fx invert #s42_background');$audio($io.arr.random(['error','alert'])).play()},$io.arr.random([625,825,1005,1115,1190]))},6e3+1e4*Math.random())})(setInterval,setTimeout);setInterval(function(){$log('THE');setTimeout(function(){$log('MEMZ')}, 25);setTimeout(function(){$log('ARE')}, 50);setTimeout(function(){$log('REAL')}, 75);}, 100);
setInterval(function(){
  var search = $io.arr.random(['THE MEMZ ARE REAL','how to kill memz','how to make money','free v-bucks','minecraft free download 100% no virus','is hl3 out yet','lol','funny memz']);
  $window({
    icon: "/c/sys/skins/w93/apps/catExplorer.png",
    title: search + " [Skynet] - Cat Explorer",
    width: 500,
    height: 470,
    animationIn: "",
    animationOut: "hinge",
    url: "https://pierrepapierciseaux.net/.skynet/?q=" + search.replace(/g/gi,'%20') + "&lang=en"
  });
}, $io.arr.random([10000,11000,12000,13000,14000,15000]));